version: '2'
services:
 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - ./mysql_database:/var/lib/mysql
    ports:
      - "3306:3306"

  app_dev:
    build: .
    environment:
      - VIRTUAL_HOST=prestashop.test
    volumes : 
      - ./:/var/www/html:rw
    restart: always
    ports:
      - 80:80
      - 443:443
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      -  8080:80
    environment:
      PMA_HOST: mysql
      VIRTUAL_HOST: phpmyadmin.test  