<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqjfabi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqjfabi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQqjfabi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQqjfabi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQqjfabi\appProdProjectContainer([
    'container.build_hash' => 'Qqjfabi',
    'container.build_id' => 'a2a2c3f4',
    'container.build_time' => 1638625774,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqjfabi');
